id: P005574
initial_creation_type: ocr
source_metadata:
  id: bdr:W21663
  title: ཉི་ཟླའི་གསོ་རིག་ཆེད་རྩོམ་གཅེས་བཏུས།
  author: ''
  volumes:
    37936c2ab7d54659a52705e30e028c2d:
      image_group_id: I1KG21894
      title: ''
      volume_number: 1
      total_pages: 262
