id: I4B0C4068
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:55:43+00:00'
last_modified: '2022-06-08T05:01:35.726468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21663
  title: ཉི་ཟླའི་གསོ་རིག་ཆེད་རྩོམ་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8FFB:
      image_group_id: I1KG21894
      title: ''
      total_pages: 262
      order: 1
      base_file: 8FFB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
